### ISSUE TITLE
Unable to view key values

### ISSUE THREAD

**Issue by M1ra1B0T** [janstarke/regview#2]
Using regview I was not able to view the keys SYSTEM\MountedDevices, SYSTEM\RNG and SYSTEM\Select, although those keys had associated values, that I could extract with other tools, like target-reg from dissect or registry explorer from eric zimmerman.
When trying to view them with regview, I dont got any values displayed.

**Comment by janstarke** [comment]
I compared the result to `regdump`. The latter prints all values. So, this is not a problem in https://github.com/dfir-dd/nt_hive2, but indeed in `regview`
