### ISSUE TITLE
Error while reading transaction logs

### ISSUE THREAD

**Issue by M1ra1B0T** [janstarke/regview#3]
I tried to load a SYSTEM hive and it's transaction logs into regview, however I received the following error message:
`Error: AssertFail at 0x0: "! log_entries.is_empty()"`
I might be wrong, but they don't seem empty to me. I tried to load the same hive with registry explorer from eric zimmerman and got the message "Primary and secondary sequence numbers do not match. This means there is uncommitted data in the transaction logs.", which is a indicator to me that the transactions logs are indeed not empty. I can provide my sample data on request.

**Comment by janstarke** [comment]
which version of `regview` do you use? I suppose that this problem has been fixed by dfir-dd/nt-hive2#14. So, this issue could be fixed by `0.4.1`

**Comment by M1ra1B0T** [comment]
Initially I tried with version 0.4.0. I tried again with version 0.4.1 and don't get the error anymore.
